#ifndef TAG_H
#define TAG_H
class Tag{
public:
	static const int IDEN,INTCON,CHARCON,STRCON,CONSTTK,INTTK,CHARTK,VARTK,ARRAYTK,OFTK,
		IFTK,THENTK,ELSETK,DOTK,WHILETK,FORTK,TOTK,BYTK,DOWNTOTK,
		PROCETK,FUNCTK,READTK,WRITETK,CALLTK,BEGINTK,ENDTK,
		PLUS,MINU,MULT,DIV,LSS,LEQ,GRE,GEQ,EQL,NEQ,ASSIGN,
		SEMICN,COMMA,PERIOD,COLON,QMARK,DQMARK,LPARENT,RPARENT,
		LBRACK,RBRACK,LBRACE,RBRACE,ILLEGALNUM,ILLEGALCHA,ILLEGALSTR;
};

#endif